
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Pramo
 */
public class GLmanual_entry extends javax.swing.JPanel {

    Interface_Events interface_events = new Interface_Events();
    DatabaseManager dbm = DatabaseManager.getDbCon();
    /**
     * Creates new form GLmanual_entry
     */
    GreenLeaf globject = new GreenLeaf();

    public GLmanual_entry() {
        initComponents();
        leaf_cat.setSelectedItem("A"); // default///////////////////////////////////////////////////////////////////////////////////////////////
    }

    public void focus() // Focus event to bring focus to the jpanel
    {
        this.requestFocusInWindow();
        category_code.requestFocusInWindow();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        supplier_id = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        self_transport = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        category_code = new javax.swing.JComboBox();
        category_name = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        no_of_sacks = new javax.swing.JTextField();
        total_kg = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        sacks_weight = new javax.swing.JTextField();
        water = new javax.swing.JTextField();
        coarse_leaf = new javax.swing.JTextField();
        other = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        net_weight = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        sendButton = new javax.swing.JButton();
        leaf_cat = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        date = new com.michaelbaranov.microba.calendar.DatePicker();

        jLabel1.setText("User ID");

        jLabel2.setText("Name ");

        jLabel3.setText("Category");

        jLabel4.setText("Leaf Category");

        DatabaseManager dbm = DatabaseManager.getDbCon();
        supplier_id.putClientProperty("JComboBox.isTableCellEditor", Boolean.TRUE);
        supplier_id.setEditable(true);
        supplier_id.setModel(new javax.swing.DefaultComboBoxModel(dbm.getStringArray("suppliers", "sup_id")));
        supplier_id.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                supplier_idItemStateChanged(evt);
            }
        });
        supplier_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplier_idActionPerformed(evt);
            }
        });
        supplier_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                supplier_idKeyReleased(evt);
            }
        });

        jLabel5.setText("Date");

        self_transport.setText(" Self Transport");
        self_transport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                self_transportActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel6.setText("No: of sacks");

        jLabel7.setText("Total(KG)");

        jLabel8.setText("Sacks weight");

        jLabel9.setText("Water");

        jLabel10.setText("Co: Leaf");

        jLabel11.setText("Other");

        jLabel12.setText("Net Weight");

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");

        jButton3.setText("Quit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));

        jButton4.setText("Supplier Status");

        jButton5.setText("Supplies");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        name.setForeground(new java.awt.Color(51, 51, 51));

        category_code.putClientProperty("JComboBox.isTableCellEditor", Boolean.TRUE);
        category_code.setEditable(true);
        category_code.setModel(new javax.swing.DefaultComboBoxModel(dbm.getStringArray("category", "category_id")));
        category_code.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                category_codeItemStateChanged(evt);
            }
        });

        category_name.setForeground(new java.awt.Color(51, 51, 51));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        no_of_sacks.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                no_of_sacksFocusLost(evt);
            }
        });
        no_of_sacks.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                no_of_sacksKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                no_of_sacksKeyReleased(evt);
            }
        });

        total_kg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_kgActionPerformed(evt);
            }
        });
        total_kg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                total_kgFocusLost(evt);
            }
        });
        total_kg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                total_kgKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                total_kgKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(no_of_sacks, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(total_kg, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(no_of_sacks, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total_kg, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        sacks_weight.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                sacks_weightFocusLost(evt);
            }
        });
        sacks_weight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sacks_weightKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sacks_weightKeyReleased(evt);
            }
        });

        water.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                waterFocusLost(evt);
            }
        });
        water.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                waterKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                waterKeyReleased(evt);
            }
        });

        coarse_leaf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                coarse_leafFocusLost(evt);
            }
        });
        coarse_leaf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                coarse_leafKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                coarse_leafKeyReleased(evt);
            }
        });

        other.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                otherFocusLost(evt);
            }
        });
        other.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                otherKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                otherKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sacks_weight, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(water, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(coarse_leaf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(other, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sacks_weight, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(water, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coarse_leaf, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(other, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        net_weight.setBackground(new java.awt.Color(204, 255, 204));
        net_weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                net_weightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(net_weight, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(net_weight, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Code", "Sacks", "Total", "S:weight", "Water", "Co:Leaf", "Other", "Net W", "Self transport", "Leaf Cat:"
            }
        ));
        jScrollPane1.setViewportView(table);

        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });
        sendButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sendButtonFocusGained(evt);
            }
        });

        leaf_cat.putClientProperty("JComboBox.isTableCellEditor", Boolean.TRUE);
        leaf_cat.setEditable(true);
        leaf_cat.setModel(new javax.swing.DefaultComboBoxModel(dbm.getStringArray("leaf_category", "category_name")));
        leaf_cat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                leaf_catItemStateChanged(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(153, 0, 0));

        jButton6.setText("Clear all");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Clear Last ");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(153, 0, 0));

        date.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dateKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dateKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(138, 138, 138)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(leaf_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(self_transport)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(category_code, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(category_name, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(supplier_id, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel7))
                                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel9)
                                                .addGap(39, 39, 39)
                                                .addComponent(jLabel10)
                                                .addGap(32, 32, 32)
                                                .addComponent(jLabel11))
                                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(sendButton)))
                                        .addGap(22, 22, 22)))))
                        .addGap(0, 220, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(category_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(category_name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(supplier_id, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(leaf_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(self_transport)))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sendButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton7)
                                .addComponent(jButton6)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void self_transportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_self_transportActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_self_transportActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // adding common data to the database
        globject.setCategoryCode(Integer.parseInt(category_code.getSelectedItem().toString()));
        java.sql.Date date1 = new java.sql.Date(date.getDate().getTime());
        globject.setDate(date1);

        // adding values in the table
        int i = 0;
        boolean st;

        while (table.getValueAt(i, 0) != null) {
            globject.setSupplierCode(Integer.parseInt((String) table.getValueAt(i, 0)));
            globject.setLeafCategory((String) table.getValueAt(i, 9));
            globject.setNoOfSacks(Integer.parseInt((String) table.getValueAt(i, 1)));
            globject.setTotalWeight(Double.parseDouble((String) table.getValueAt(i, 2)));
            globject.setSacksWeight(Double.parseDouble((String) table.getValueAt(i, 3)));
            globject.setWater(Double.parseDouble((String) table.getValueAt(i, 4)));
            globject.setCoarseLeaf(Double.parseDouble((String) table.getValueAt(i, 5)));
            globject.setOther(Double.parseDouble((String) table.getValueAt(i, 6)));
            globject.setNetQuantity(Double.parseDouble((String) table.getValueAt(i, 7)));
            if ("Yes".equals((String) table.getValueAt(i, 8))) {
                st = true;
            } else {
                st = false;
            }
            globject.setSelfTransport(st);
            globject.setIntselfTransport(globject.getSelfTransport());

            globject.addToDataBase();

            i++;
        }
        int k = 0;
        int j = 0;
        while (table.getValueAt(k, 0) != null) {

            j = 0;
            while (j < 10) {

                table.setValueAt(null, k, j);
                j++;
            }
            k++;
        }
        category_code.setEnabled(true);
        date.setEnabled(true);
        category_name.setText(" ");

        category_code.requestFocusInWindow();
        category_code.setSelectedItem(null);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void supplier_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplier_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplier_idActionPerformed

    private void net_weightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_net_weightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_net_weightActionPerformed

    private void supplier_idItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_supplier_idItemStateChanged
        DatabaseManager dbm = DatabaseManager.getDbCon();
        String Name = null;
        String category = null;
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            int item = Integer.parseInt(evt.getItem().toString());
            try {
                ResultSet query = dbm.query("SELECT * FROM suppliers WHERE sup_id =" + item + "");
                while (query.next()) {
                    Name = query.getString("sup_name");
                }
            } catch (SQLException ex) {
            }
            
             try {
                ResultSet query = dbm.query("SELECT * FROM suppliers WHERE sup_id =" + item + "");
                while (query.next()) {
                    category = query.getString("cat_id");
                }
            } catch (SQLException ex) {
            }
             
             
      if(!category_code.getSelectedItem().toString().equals(category))
      {
          JOptionPane.showMessageDialog(other, "Supplier Category Exception!");
          
      }
             
            name.setText("" + Name);

            no_of_sacks.requestFocusInWindow();

            jLabel14.setText(" ");

            // do something with object
       }    }//GEN-LAST:event_supplier_idItemStateChanged

    private void category_codeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_category_codeItemStateChanged
        DatabaseManager dbm = DatabaseManager.getDbCon();
        String Name = null;
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String item = evt.getItem().toString();
            try {
                ResultSet query = dbm.query("SELECT * FROM category WHERE category_id =" + item + "");
                while (query.next()) {
                    Name = query.getString("category_name");
                }
            } catch (SQLException ex) {
            }
            category_name.setText("" + Name);
        }
        date.requestFocusInWindow();
        jPanel6.setBackground(new java.awt.Color(0, 102, 0));


    }//GEN-LAST:event_category_codeItemStateChanged

    private void no_of_sacksKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_no_of_sacksKeyReleased

    }//GEN-LAST:event_no_of_sacksKeyReleased

    private void no_of_sacksFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_no_of_sacksFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_no_of_sacksFocusLost

    private void total_kgFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_total_kgFocusLost
        net_weight.setText("" + ((convertString(total_kg.getText())) - (convertString(sacks_weight.getText())) - (convertString(water.getText())) - (convertString(coarse_leaf.getText())) - (convertString(other.getText()))));

    }//GEN-LAST:event_total_kgFocusLost

    private void total_kgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_kgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_kgActionPerformed

    private void sacks_weightFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sacks_weightFocusLost
        net_weight.setText("" + ((convertString(total_kg.getText())) - (convertString(sacks_weight.getText())) - (convertString(water.getText())) - (convertString(coarse_leaf.getText())) - (convertString(other.getText()))));
    }//GEN-LAST:event_sacks_weightFocusLost

    private void waterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_waterFocusLost
        net_weight.setText("" + ((convertString(total_kg.getText())) - (convertString(sacks_weight.getText())) - (convertString(water.getText())) - (convertString(coarse_leaf.getText())) - (convertString(other.getText()))));

    }//GEN-LAST:event_waterFocusLost

    private void coarse_leafFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_coarse_leafFocusLost
        net_weight.setText("" + ((convertString(total_kg.getText())) - (convertString(sacks_weight.getText())) - (convertString(water.getText())) - (convertString(coarse_leaf.getText())) - (convertString(other.getText()))));

    }//GEN-LAST:event_coarse_leafFocusLost

    private void otherFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_otherFocusLost
        net_weight.setText("" + ((convertString(total_kg.getText())) - (convertString(sacks_weight.getText())) - (convertString(water.getText())) - (convertString(coarse_leaf.getText())) - (convertString(other.getText()))));

    }//GEN-LAST:event_otherFocusLost

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed

        if (supplier_id.getSelectedItem() == null) {
            jLabel14.setText("Please Choose Supplir ID");
        } else if (leaf_cat.getSelectedItem() == null) {
            jLabel15.setText("Please Choose Leaf Category");
        } else {

            int i = 0;
            while (table.getValueAt(i, 0) != null) {
                i++;
            }
            int j = 0;
            Boolean if_equal_return_1 = false;
            while (j<i) {
                      if(supplier_id.getSelectedItem().toString().equals(table.getValueAt(j, 0))){
                if_equal_return_1 = true ;
                      }

                j++;
            }

            if (if_equal_return_1) {

                //JOptionPane.showConfirmDialog(category_code, "Duplicate Supplier code! Confirm?");
                int reply = JOptionPane.showConfirmDialog(other,
                        "Duplicate Supplier ID"+"\n"+"Cancel?", "Duplicate ID", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.NO_OPTION) {
                    table.setValueAt(supplier_id.getSelectedItem().toString(), i, 0);
                    table.setValueAt(leaf_cat.getSelectedItem().toString(), i, 9);
                    table.setValueAt(no_of_sacks.getText(), i, 1);
                    table.setValueAt(total_kg.getText(), i, 2);
                    table.setValueAt(sacks_weight.getText(), i, 3);
                    table.setValueAt(water.getText(), i, 4);
                    table.setValueAt(coarse_leaf.getText(), i, 5);
                    table.setValueAt(other.getText(), i, 6);
                    table.setValueAt(net_weight.getText(), i, 7);
                    if (self_transport.isSelected() == true) {
                        table.setValueAt("Yes", i, 8);
                    } else {
                        table.setValueAt("No", i, 8);
                    }

                } else if (reply == JOptionPane.YES_OPTION) {

                }

            } else {

                table.setValueAt(supplier_id.getSelectedItem().toString(), i, 0);
                table.setValueAt(leaf_cat.getSelectedItem().toString(), i, 9);
                table.setValueAt(no_of_sacks.getText(), i, 1);
                table.setValueAt(total_kg.getText(), i, 2);
                table.setValueAt(sacks_weight.getText(), i, 3);
                table.setValueAt(water.getText(), i, 4);
                table.setValueAt(coarse_leaf.getText(), i, 5);
                table.setValueAt(other.getText(), i, 6);
                table.setValueAt(net_weight.getText(), i, 7);
                if (self_transport.isSelected() == true) {
                    table.setValueAt("Yes", i, 8);

                } else {
                    table.setValueAt("No", i, 8);
                }
            }
            supplier_id.requestFocusInWindow(); // request focus
            supplier_id.setSelectedItem(null);   // setting null
            leaf_cat.setSelectedItem("A"); // default///////////////////////////////////////////////////////////////////////////////////////////////
            no_of_sacks.setText(null);
            total_kg.setText(null);
            sacks_weight.setText(null);
            water.setText(null);
            coarse_leaf.setText(null);
            other.setText(null);
            net_weight.setText(null);

            category_code.setEnabled(false);
            date.setEnabled(false);
            name.setText(" ");

        }
        //debit_amount.setText(null);
    }//GEN-LAST:event_sendButtonActionPerformed

    private void supplier_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supplier_idKeyReleased


    }//GEN-LAST:event_supplier_idKeyReleased

    private void leaf_catItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_leaf_catItemStateChanged
        no_of_sacks.requestFocusInWindow();
        jLabel15.setText(" ");
    }//GEN-LAST:event_leaf_catItemStateChanged

    private void total_kgKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_total_kgKeyReleased

    }//GEN-LAST:event_total_kgKeyReleased

    private void sacks_weightKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sacks_weightKeyReleased

    }//GEN-LAST:event_sacks_weightKeyReleased

    private void waterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_waterKeyReleased

    }//GEN-LAST:event_waterKeyReleased

    private void coarse_leafKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_coarse_leafKeyReleased

    }//GEN-LAST:event_coarse_leafKeyReleased

    private void otherKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_otherKeyReleased

    }//GEN-LAST:event_otherKeyReleased

    private void sendButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sendButtonFocusGained
        interface_events.Respond_enter(sendButton, evt);        // TODO add your handling code here:
    }//GEN-LAST:event_sendButtonFocusGained

    private void no_of_sacksKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_no_of_sacksKeyPressed
        interface_events.Change_focus_Enterkey_t(no_of_sacks, evt);
        interface_events.Change_focus_Enterkey_t(total_kg, evt);
    }//GEN-LAST:event_no_of_sacksKeyPressed

    private void total_kgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_total_kgKeyPressed
        interface_events.Change_focus_Enterkey_t(sacks_weight, evt);
    }//GEN-LAST:event_total_kgKeyPressed

    private void sacks_weightKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sacks_weightKeyPressed
        interface_events.Change_focus_Enterkey_t(water, evt);
    }//GEN-LAST:event_sacks_weightKeyPressed

    private void waterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_waterKeyPressed
        interface_events.Change_focus_Enterkey_t(coarse_leaf, evt);
    }//GEN-LAST:event_waterKeyPressed

    private void coarse_leafKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_coarse_leafKeyPressed
        interface_events.Change_focus_Enterkey_t(other, evt);
    }//GEN-LAST:event_coarse_leafKeyPressed

    private void otherKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_otherKeyPressed
        interface_events.Change_focus_Enterkey_t_b(other, sendButton, evt);
    }//GEN-LAST:event_otherKeyPressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int i = 0;
        int j = 0;
        while (table.getValueAt(i, 0) != null) {

            j = 0;
            while (j < 10) {

                table.setValueAt(null, i, j);
                j++;
            }
            i++;
        }


    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int i = 0;
        int j = 0;
        while (table.getValueAt(i, 0) != null) {
            i++;
        }
        i--;
        while (j < 10) {
            table.setValueAt(null, i, j);
            j++;

        }


    }//GEN-LAST:event_jButton7ActionPerformed

    private void dateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateKeyReleased


    }//GEN-LAST:event_dateKeyReleased

    private void dateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateKeyPressed
        interface_events.Change_focus_Enterkey_c(supplier_id, evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jPanel6.setBackground(new java.awt.Color(240, 240, 240));
        }

    }//GEN-LAST:event_dateKeyPressed
    public double convertString(String s) {
        if (s.length() == 0) {
            return 0;
        } else {
            return Double.parseDouble(s);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox category_code;
    private javax.swing.JLabel category_name;
    private javax.swing.JTextField coarse_leaf;
    private com.michaelbaranov.microba.calendar.DatePicker date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JComboBox leaf_cat;
    private javax.swing.JLabel name;
    private javax.swing.JTextField net_weight;
    private javax.swing.JTextField no_of_sacks;
    private javax.swing.JTextField other;
    private javax.swing.JTextField sacks_weight;
    private javax.swing.JCheckBox self_transport;
    private javax.swing.JButton sendButton;
    private javax.swing.JComboBox supplier_id;
    private javax.swing.JTable table;
    private javax.swing.JTextField total_kg;
    private javax.swing.JTextField water;
    // End of variables declaration//GEN-END:variables
}
